{{- if .Values.alertmanager.enabled }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: {{ include "myapp.fullname" . }}-alerts
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  route:
    groupBy: ['alertname', 'severity']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
    receiver: 'email-notifications'
    routes:
    - matchers:
      - name: severity
        value: warning
      receiver: 'email-notifications'
  receivers:
  - name: 'email-notifications'
    emailConfigs:
    - to: 'alerts@example.com'
      from: 'alertmanager@example.com'
      smarthost: 'smtp.example.com:587'
      authUsername: 'alertmanager'
      authPassword:
        name: {{ include "myapp.fullname" . }}-secret
        key: smtpPassword
      requireTLS: true
      sendResolved: true
{{- end }} 