apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-config
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  modelServiceUrl: http://{{ if .Values.namePrefix }}{{ .Values.namePrefix }}-{{ .Values.modelService.name }}{{ else }}{{ .Values.modelService.name }}{{ end }}:{{ .Values.modelService.port }}