apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}-myapp
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myapp.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp.labels" . | nindent 8 }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "{{ .Values.service.targetPort }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.appImage.repository }}:{{ .Values.appImage.tag }}"
          imagePullPolicy: {{ .Values.appImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          env:
            - name: MODEL_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "myapp.fullname" . }}-config
                  key: modelServiceUrl
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "myapp.fullname" . }}-secret
                  key: smtpPassword
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.namePrefix }}-model-service
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    app: model-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-service
      {{- include "myapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: model-service
        {{- include "myapp.labels" . | nindent 8 }}
    spec:
      containers:
        - name: model-service
          image: "{{ .Values.modelImage.repository }}:{{ .Values.modelImage.tag }}"
          imagePullPolicy: {{ .Values.modelImage.pullPolicy }}
          ports:
            - containerPort: {{ .Values.modelService.targetPort }}
              name: http
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"