{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "myapp.fullname" . }}
  namespace: default
spec:
  host: {{ .Values.service.name }}-{{ include "myapp.fullname" . }}
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
{{- end }}