{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.host | default (printf "%s.myapp.local" .Release.Name) }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name }}-{{ include "myapp.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}