{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "myapp.fullname" . }}-rules
  namespace: monitoring
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
    {{- with .Values.prometheusRules.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
  - name: {{ include "myapp.fullname" . }}.rules
    rules:
    - alert: HighRequestRate
      expr: sum(rate(flask_http_request_total{service="{{ .Values.service.name }}-{{ include "myapp.fullname" . }}"}[1m])) > 15
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High request rate detected"
        description: "Service {{ .Values.service.name }}-{{ include "myapp.fullname" . }} has received more than 15 requests per minute for the last 2 minutes"
        runbook_url: "https://example.com/runbooks/high-traffic"
{{- end }} 