apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}-{{ .Values.service.name }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "myapp.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.namePrefix }}-{{ .Values.modelService.name }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.modelService.type }}
  ports:
    - port: {{ .Values.modelService.port }}
      targetPort: {{ .Values.modelService.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: model-service
