{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "myapp.fullname" . }}-vs
  namespace: default
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  hosts:
  - "{{ .Values.istio.host | default "app.local" }}"
  gateways:
  - istio-ingress/{{ include "myapp.fullname" . }}-gateway
  http:
  # Sticky Sessions: Route users with specific header to v2
  - match:
    - headers:
        x-user-id:
          exact: "{{ .Values.istio.sticky.userId | default "test-user" }}"
    route:
    - destination:
        host: {{ .Values.service.name }}-{{ include "myapp.fullname" . }}
        subset: v2
      weight: 100
    headers:
      response:
        add:
          x-served-by: "version-v2-sticky"
          x-routing-type: "sticky-session"
  # Default Canary routing: 90% v1, 10% v2
  - route:
    - destination:
        host: {{ .Values.service.name }}-{{ include "myapp.fullname" . }}
        subset: v1
      weight: {{ .Values.istio.canary.v1Weight | default 90 }}
      headers:
        response:
          add:
            x-served-by: "version-v1"
            x-routing-type: "canary-primary"
    - destination:
        host: {{ .Values.service.name }}-{{ include "myapp.fullname" . }}
        subset: v2
      weight: {{ .Values.istio.canary.v2Weight | default 10 }}
      headers:
        response:
          add:
            x-served-by: "version-v2-canary"
            x-routing-type: "canary-treatment"
{{- end }}
