{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "myapp.fullname" . }}-vs
  namespace: default
spec:
  hosts:
  - "{{ .Values.istio.host }}"
  gateways:
  - istio-ingress/{{ include "myapp.fullname" . }}-gateway
  http:
  # Route specific test user to v2
  - match:
    - headers:
        x-user-id:
          exact: "{{ .Values.istio.sticky.userId }}"
    route:
    - destination:
        host: {{ .Values.namePrefix }}-{{ .Values.service.name }}
        subset: v2
    headers:
      response:
        set:
          Set-Cookie: "version=v2; Path=/; Max-Age=3600; HttpOnly"

  # Direct route static assets based on the version cookie if present
  - match:
    - uri:
        prefix: "/static/"
      headers:
        cookie:
          regex: ".*version=v1.*"
    route:
    - destination:
        host: {{ .Values.namePrefix }}-{{ .Values.service.name }}
        subset: v1

  - match:
    - uri:
        prefix: "/static/"
      headers:
        cookie:
          regex: ".*version=v2.*"
    route:
    - destination:
        host: {{ .Values.namePrefix }}-{{ .Values.service.name }}
        subset: v2

  # For static assets without a version cookie, use 90/10 distribution
  - match:
    - uri:
        prefix: "/static/"
    route:
    - destination:
        host: {{ .Values.namePrefix }}-{{ .Values.service.name }}
        subset: v1
      weight: 90
    - destination:
        host: {{ .Values.namePrefix }}-{{ .Values.service.name }}
        subset: v2
      weight: 10
           
  # For main app traffic, use 90/10 distribution
  - route:
    - destination:
        host: {{ .Values.namePrefix }}-{{ .Values.service.name }}
        subset: v1
      weight: 90
      headers:
        response:
          set:
            Set-Cookie: "version=v1; Path=/; Max-Age=3600; HttpOnly"
    - destination:
        host: {{ .Values.namePrefix }}-{{ .Values.service.name }}
        subset: v2
      weight: 10
      headers:
        response:
          set:
            Set-Cookie: "version=v2; Path=/; Max-Age=3600; HttpOnly"
    corsPolicy:
      allowOrigins:
      - exact: "http://{{ .Values.istio.host }}"
---
# Internal VirtualService for model-service routing based on source app version
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ include "myapp.fullname" . }}-model-vs
  namespace: default
spec:
  hosts:
  - {{ .Values.namePrefix }}-{{ .Values.modelService.name }}
  http:
  - match:
    - sourceLabels:
        version: v2
    route:
    - destination:
        host: {{ .Values.namePrefix }}-{{ .Values.modelService.name }}
        subset: v2
{{- if .Values.shadowLaunch.enabled }}
    mirror:
      host: {{ .Values.namePrefix }}-{{ .Values.modelService.name }}
      subset: shadow
    mirrorPercentage:
      value: {{ .Values.shadowLaunch.mirrorPercentage | default 100.0 }}
{{- end }}
  - route: # default route for v1 and any other traffic
    - destination:
        host: {{ .Values.namePrefix }}-{{ .Values.modelService.name }}
        subset: v1
{{- if .Values.shadowLaunch.enabled }}
    mirror:
      host: {{ .Values.namePrefix }}-{{ .Values.modelService.name }}
      subset: shadow
    mirrorPercentage:
      value: {{ .Values.shadowLaunch.mirrorPercentage | default 100.0 }}
{{- end }}
{{- end }}