services:
  app-service:
    # build:
    #   context: ../app 
    #   dockerfile: Dockerfile
    image: ${APP_SERVICE_IMAGE}:${APP_SERVICE_VERSION}
    # build: https://github.com/remla25-team8/app.git
    ports:
      # - "8080:8080"
      - "${APP_SERVICE_PORT}:${APP_SERVICE_PORT}"
    environment:
      # - MODEL_SERVICE_URL=http://192.168.0.103:5000
      # - MODEL_SERVICE_URL=http://model-service:5000
      - MODEL_SERVICE_URL=http://model-service:${MODEL_SERVICE_PORT}
      - PORT=${APP_SERVICE_PORT}
      - APP_VERSION=${APP_SERVICE_VERSION}
      - MODEL_SERVICE_VERSION=${MODEL_SERVICE_VERSION}
    # depends_on:
      # - model-service
    volumes:
      # - ../app:/root/app 
      - .:/root/mount # not used if we use the image from the registry
    restart: always
    networks:
      - app-network

  model-service:
    # build:
    #   context: ../model-service 
    #   dockerfile: Dockerfile
    image: ${MODEL_SERVICE_IMAGE}:${MODEL_SERVICE_VERSION}
    # build: https://github.com/remla25-team8/model-service.git
    ports:
      # - "5000:5000" 
      - "${MODEL_SERVICE_PORT}:${MODEL_SERVICE_PORT}"
    environment:
      - FLASK_ENV=production
      - PORT=${MODEL_SERVICE_PORT}
      - HOST=0.0.0.0
    volumes:
      # - ../model-service:/root/app
      - .:/root/mount # not used if we use the image from the registry
    restart: always 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge