---
# This playbook will run after all nodes have been configured.
# And the Kubernetes cluster has been initialized.

- hosts: all
  become: true
  vars:
    kubeconfig: /etc/kubernetes/admin.conf
  tasks:
    # Install required Python packages for kubernetes.core.k8s module
    - name: Install python3-kubernetes package
      apt:
        name: python3-kubernetes
        state: present
        update_cache: yes
      become: true
      become_user: root

    # Step 20: Install MetalLB using Helm
    - name: Add MetalLB Helm repository
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb
        kubeconfig: "{{ kubeconfig }}"

    - name: Install MetalLB using Helm
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        release_namespace: metallb-system
        create_namespace: true
        kubeconfig: "{{ kubeconfig }}"
        chart_version: "0.14.9"

    - name: Wait for MetalLB controller to be ready
      shell: kubectl --kubeconfig={{ kubeconfig }} wait -n metallb-system -l app.kubernetes.io/name=metallb,app.kubernetes.io/component=controller --for=condition=ready pod --timeout=60s
      changed_when: false

    - name: Create MetalLB IP address pool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: first-pool
            namespace: metallb-system
          spec:
            addresses:
              - 192.168.56.90-192.168.56.99
        kubeconfig: "{{ kubeconfig }}"

    - name: Create MetalLB L2 advertisement
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: example
            namespace: metallb-system
          spec:
            ipAddressPools:
              - first-pool
        kubeconfig: "{{ kubeconfig }}"

    # Step 21: Install Nginx Ingress Controller
    - name: Add Nginx Ingress Helm repository
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx
        kubeconfig: "{{ kubeconfig }}"  

    - name: Install Nginx Ingress Controller
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        kubeconfig: "{{ kubeconfig }}" 
        values:
          controller:
            service:
              loadBalancerIP: 192.168.56.90

    - name: Wait for Nginx Ingress Controller to be ready
      shell: kubectl --kubeconfig={{ kubeconfig }} wait -n ingress-nginx -l app.kubernetes.io/name=ingress-nginx,app.kubernetes.io/component=controller --for=condition=ready pod --timeout=120s
      changed_when: false

    # Step 22: Install Kubernetes Dashboard
    - name: Add Kubernetes Dashboard Helm repository
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard
        kubeconfig: "{{ kubeconfig }}"  

    - name: Create kubernetes-dashboard namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: kubernetes-dashboard
        kubeconfig: "{{ kubeconfig }}"

    - name: Create Kong configuration ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: kong-config
            namespace: kubernetes-dashboard
          data:
            KONG_SSL: "on"
            KONG_SSL_CERT: "/etc/secrets/tls.crt"
            KONG_SSL_CERT_KEY: "/etc/secrets/tls.key"
        kubeconfig: "{{ kubeconfig }}"

    - name: Install Kubernetes Dashboard with Kong configuration
      kubernetes.core.helm:
        name: kubernetes-dashboard
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        release_namespace: kubernetes-dashboard
        create_namespace: false
        kubeconfig: "{{ kubeconfig }}"
        values:
          kong:
            enabled: true
            env:
              KONG_SSL: "on"
              KONG_SSL_CERT: "/etc/secrets/tls.crt"
              KONG_SSL_CERT_KEY: "/etc/secrets/tls.key"
            service:
              type: LoadBalancer
              ports:
                kong-proxy-tls:
                  port: 443
                  targetPort: 8443
                  protocol: TCP

    - name: Create admin user for Dashboard
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: admin-user
            namespace: kubernetes-dashboard
        kubeconfig: "{{ kubeconfig }}"

    - name: Create cluster role binding for admin user
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: admin-user
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
          - kind: ServiceAccount
            name: admin-user
            namespace: kubernetes-dashboard
        kubeconfig: "{{ kubeconfig }}"

    - name: Create Ingress for Kubernetes Dashboard
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: kubernetes-dashboard
            namespace: kubernetes-dashboard
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
              nginx.ingress.kubernetes.io/ssl-redirect: "true"
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          spec:
            ingressClassName: nginx
            tls:
            - hosts:
              - dashboard.local
            rules:
            - host: dashboard.local
              http:
                paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: kubernetes-dashboard-kong-proxy
                      port:
                        number: 443
        kubeconfig: "{{ kubeconfig }}"

    - name: Wait for Kong proxy to be ready
      shell: kubectl --kubeconfig={{ kubeconfig }} wait -n kubernetes-dashboard -l app.kubernetes.io/name=kong --for=condition=ready pod --timeout=120s
      changed_when: false

    - name: Instructions to access Dashboard
      debug:
        msg:
          - "Dashboard has been deployed. To access it:"
          - "1. Add 'dashboard.local' to your hosts file pointing to 192.168.56.90"
          - "2. Run this command to get a login token: kubectl -n kubernetes-dashboard create token admin-user"
          - "3. Access the dashboard at https://dashboard.local (note: using HTTPS)"
          - "4. You may need to accept the self-signed certificate warning in your browser"
