# ---
# # This playbook contains specific tasks for worker nodes.
# # It will be executed only on worker nodes as part of the playbook general.yaml

# - name: Placeholder for worker node specific tasks
#   debug:
#     msg: "Worker node specific provisioning will be configured in later steps"

---
- name: Configure Kubernetes worker nodes
  hosts: worker
  gather_facts: yes
  become: true
  tasks:
    # Step 18 - Check if the node is already part of the cluster
    - name: Check if node is already part of the cluster
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_config_exists

    #Step 18 - Generate the join command
    - name: Generate Kubernetes join command on controller
      command: kubeadm token create --print-join-command
      delegate_to: "{{ groups['controller'][0] }}"
      run_once: true
      register: join_cmd
      when: not kubelet_config_exists.stat.exists

    # Step 19 - Join the worker node to the cluster
    # - name: Join the Kubernetes cluster
    #   # shell: "{{ join_cmd.stdout }}"
    #   ansible.builtin.shell: "{{ join_cmd.stdout }}"
    #   args:
    #     warn: false
    #   when: not kubelet_config_exists.stat.exists
    - name: Join the Kubernetes cluster
      ansible.builtin.shell:
        cmd: "{{ join_cmd.stdout }}"
      become: true
      when: not kubelet_config_exists.stat.exists
